"""Asynchronous indexing of prepared knowledge documents into Qdrant."""
from __future__ import annotations

import asyncio
import uuid
from collections.abc import Sequence
from typing import Any

from .schema import (
    BM25_MODEL,
    BM25_VECTOR_NAME,
    DENSE_VECTOR_NAME,
    EMBEDDING_DIMENSIONS,
    collection_name,
    embedding_model,
    qdrant_client_options,
)


class KnowledgeIndexError(RuntimeError):
    """An indexing failure that can be shown safely in the settings UI."""


def _make_client(settings):
    from qdrant_client import QdrantClient

    return QdrantClient(**qdrant_client_options(settings))


def _ensure_collection(client, name: str) -> None:
    from qdrant_client.models import Distance, Modifier, SparseVectorParams, VectorParams

    collections = client.get_collections()
    if any(item.name == name for item in collections.collections):
        return
    client.create_collection(
        collection_name=name,
        vectors_config={
            DENSE_VECTOR_NAME: VectorParams(size=EMBEDDING_DIMENSIONS, distance=Distance.COSINE),
        },
        sparse_vectors_config={
            BM25_VECTOR_NAME: SparseVectorParams(modifier=Modifier.IDF),
        },
    )


def _replace_vault_documents(client, name: str, vault_path: str, points: Sequence[Any]) -> None:
    """Replace one vault atomically enough for deterministic, stale-free syncs."""
    from qdrant_client.models import FieldCondition, Filter, MatchValue

    client.delete(
        collection_name=name,
        points_selector=Filter(
            must=[FieldCondition(key="vault", match=MatchValue(value=vault_path))],
        ),
        wait=True,
    )
    if points:
        client.upsert(collection_name=name, points=points, wait=True)


async def index_documents(documents: Sequence[dict[str, Any]], vault_path: str, *, settings=None) -> str:
    """Embed and index document chunks without blocking the API event loop.

    Dense vectors come from OpenAI.  The named ``bm25`` vector is generated by
    Qdrant from the same text, and Qdrant maintains the corpus-wide IDF values.
    Deterministic point IDs plus replacement by vault prevent duplicate and
    stale chunks after a re-sync.
    """
    if settings is None:
        from ..core.config import get_settings

        settings = get_settings()
    if not getattr(settings, "qdrant_url", None):
        raise KnowledgeIndexError("Qdrant is not configured. Set QDRANT_URL and start the Qdrant service.")
    if not getattr(settings, "openai_api_key", None):
        raise KnowledgeIndexError("OpenAI embeddings require OPENAI_API_KEY.")

    try:
        from openai import AsyncOpenAI
        from qdrant_client.models import Document, PointStruct

        client = await asyncio.to_thread(_make_client, settings)
        name = collection_name(settings)
        await asyncio.to_thread(_ensure_collection, client, name)
        openai = AsyncOpenAI(api_key=settings.openai_api_key)
        points: list[Any] = []
        model = embedding_model(settings)
        for start in range(0, len(documents), 96):
            batch = documents[start:start + 96]
            response = await openai.embeddings.create(
                input=[document["text"] for document in batch], model=model,
            )
            for document, embedding in zip(batch, response.data):
                content = document["text"]
                metadata = document["metadata"]
                points.append(PointStruct(
                    id=str(uuid.uuid5(uuid.NAMESPACE_URL, f"obsidian:{vault_path}:{document['id']}")),
                    vector={
                        DENSE_VECTOR_NAME: embedding.embedding,
                        BM25_VECTOR_NAME: Document(text=content, model=BM25_MODEL),
                    },
                    payload={
                        "source": "obsidian",
                        "vault": vault_path,
                        "document_id": document["id"],
                        "title": metadata.get("title", ""),
                        "path": metadata.get("path", ""),
                        "heading_path": list(metadata.get("heading_path", ())),
                        "chunk_index": metadata.get("chunk_index", 0),
                        "text": content,
                    },
                ))
        await asyncio.to_thread(_replace_vault_documents, client, name, vault_path, points)
        return f"Indexed {len(points)} chunks to Qdrant"
    except KnowledgeIndexError:
        raise
    except Exception as error:
        raise KnowledgeIndexError(f"Qdrant indexing failed: {error}") from error
