export { IntegrationsTab } from './IntegrationsTab'
export { PersonalTab } from './PersonalTab'
export { VoiceTab } from './VoiceTab'
export { AboutTab } from './AboutTab'
export { QuickNotesTab } from './QuickNotesTab'
export { RemindersTab } from './RemindersTab'
